### ISSUE TITLE
Todo ffi.md

### ISSUE THREAD

**Issue by kgv** [kgv/rust_book_ru#39]
https://github.com/kgv/rust_book_ru/blob/master/patch/ffi.md.patch
- [ ] so specifying it correctly is part of keeping the binding correct at runtime.
- [ ] Native dynamic libraries and frameworks are propagated to the final artifact boundary, while static libraries are not propagated at all.
- [ ] "nullable pointer optimization"
