### ISSUE TITLE
Todo documentation.md

### ISSUE THREAD

**Issue by kgv** [kgv/rust_book_ru#41]
- [x] Unrecoverable misuses
- [x] and can have more than one section:
- [x] Small examples often trigger these lints.
- [ ] Sometimes, this isn't enough, though. For example, all of these code samples with `///` we've been talking about

**Comment by mkpankov** [comment]
Не забыть залить свои небольшие изменения после того как решим #153
